name: Build Resume PDF

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install wkhtmltopdf
        run: sudo apt-get update && sudo apt-get install -y wkhtmltopdf

      - name: Convert HTML to PDF
        run: |
          mkdir -p assets
          wkhtmltopdf --enable-local-file-access file://$(pwd)/index.html assets/resume.pdf

      - name: Commit PDF
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add assets/resume.pdf
          git diff --quiet && git diff --staged --quiet || git commit -m "Update resume PDF"
          git push
