name: Deploy Resume to GitHub Pages

on:
  push:
    paths:
      - "resume.html"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload resume.html
        uses: actions/upload-pages-artifact@v1
        with:
          path: resume.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
