name: Deploy Resume to GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    paths:
      - "resume.html"
      - ".github/workflows/deploy-resume.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare artifact
        run: |
          mkdir -p artifact
          cp resume.html artifact/

      - name: Upload resume.html
        uses: actions/upload-pages-artifact@v3
        with:
          path: artifact

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
